package pojo;
// Generated 19 f�vr. 2019 12:38:57 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Integer codeDoc;
     private Utilisateur utilisateur;
     private String lienDoc;
     private String libelleDoc;

    public Documents() {
    }

    public Documents(Utilisateur utilisateur, String lienDoc, String libelleDoc) {
       this.utilisateur = utilisateur;
       this.lienDoc = lienDoc;
       this.libelleDoc = libelleDoc;
    }
   
    public Integer getCodeDoc() {
        return this.codeDoc;
    }
    
    public void setCodeDoc(Integer codeDoc) {
        this.codeDoc = codeDoc;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getLienDoc() {
        return this.lienDoc;
    }
    
    public void setLienDoc(String lienDoc) {
        this.lienDoc = lienDoc;
    }
    public String getLibelleDoc() {
        return this.libelleDoc;
    }
    
    public void setLibelleDoc(String libelleDoc) {
        this.libelleDoc = libelleDoc;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 73 * hash + Objects.hashCode(this.codeDoc);
        hash = 73 * hash + Objects.hashCode(this.libelleDoc);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Documents other = (Documents) obj;
        if (!Objects.equals(this.libelleDoc, other.libelleDoc)) {
            return false;
        }
        if (!Objects.equals(this.codeDoc, other.codeDoc)) {
            return false;
        }
        return true;
    }




}


