package pojo;
// Generated 19 févr. 2019 12:38:57 by Hibernate Tools 4.3.1



/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Integer codeDoc;
     private Utilisateur utilisateur;
     private String lienDoc;
     private String libelleDoc;

    public Documents() {
    }

    public Documents(Utilisateur utilisateur, String lienDoc, String libelleDoc) {
       this.utilisateur = utilisateur;
       this.lienDoc = lienDoc;
       this.libelleDoc = libelleDoc;
    }
   
    public Integer getCodeDoc() {
        return this.codeDoc;
    }
    
    public void setCodeDoc(Integer codeDoc) {
        this.codeDoc = codeDoc;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getLienDoc() {
        return this.lienDoc;
    }
    
    public void setLienDoc(String lienDoc) {
        this.lienDoc = lienDoc;
    }
    public String getLibelleDoc() {
        return this.libelleDoc;
    }
    
    public void setLibelleDoc(String libelleDoc) {
        this.libelleDoc = libelleDoc;
    }




}


