package pojo;
// Generated 20 fvr. 2019 13:58:26 by Hibernate Tools 4.3.1

import java.util.Objects;


/**
 * ExerciceDeBilan generated by hbm2java
 */
public class ExerciceDeBilan  implements java.io.Serializable {


     private ExerciceDeBilanId id;
     private Exercice exercice;
     private SeanceBilan seanceBilan;
     private Integer tempsMax;
     private Integer repsMax;
     private boolean fini;

    public ExerciceDeBilan() {
    }

	
    public ExerciceDeBilan(ExerciceDeBilanId id, Exercice exercice, SeanceBilan seanceBilan, boolean fini) {
        this.id = id;
        this.exercice = exercice;
        this.seanceBilan = seanceBilan;
        this.fini = fini;
    }
    public ExerciceDeBilan(ExerciceDeBilanId id, Exercice exercice, SeanceBilan seanceBilan, Integer tempsMax, Integer repsMax, boolean fini) {
       this.id = id;
       this.exercice = exercice;
       this.seanceBilan = seanceBilan;
       this.tempsMax = tempsMax;
       this.repsMax = repsMax;
       this.fini = fini;
    }
   
    public ExerciceDeBilanId getId() {
        return this.id;
    }
    
    public void setId(ExerciceDeBilanId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public SeanceBilan getSeanceBilan() {
        return this.seanceBilan;
    }
    
    public void setSeanceBilan(SeanceBilan seanceBilan) {
        this.seanceBilan = seanceBilan;
    }
    public Integer getTempsMax() {
        return this.tempsMax;
    }
    
    public void setTempsMax(Integer tempsMax) {
        this.tempsMax = tempsMax;
    }
    public Integer getRepsMax() {
        return this.repsMax;
    }
    
    public void setRepsMax(Integer repsMax) {
        this.repsMax = repsMax;
    }
    public boolean isFini() {
        return this.fini;
    }
    
    public void setFini(boolean fini) {
        this.fini = fini;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ExerciceDeBilan other = (ExerciceDeBilan) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


