package pojo;
// Generated 19 f�vr. 2019 12:38:57 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * ExerciceDeSeance generated by hbm2java
 */
public class ExerciceDeSeance  implements java.io.Serializable {


     private ExerciceDeSeanceId id;
     private Exercice exercice;
     private Seance seance;
     private double tempsExSc;
     private int repsExSc;
     private String evaluation;
     private String avisLibre;

    public ExerciceDeSeance() {
    }

	
    public ExerciceDeSeance(ExerciceDeSeanceId id, Exercice exercice, Seance seance, double tempsExSc, int repsExSc, String avisLibre) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
        this.tempsExSc = tempsExSc;
        this.repsExSc = repsExSc;
        this.avisLibre = avisLibre;
    }
    public ExerciceDeSeance(ExerciceDeSeanceId id, Exercice exercice, Seance seance, double tempsExSc, int repsExSc, String evaluation, String avisLibre) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.tempsExSc = tempsExSc;
       this.repsExSc = repsExSc;
       this.evaluation = evaluation;
       this.avisLibre = avisLibre;
    }
   
    public ExerciceDeSeanceId getId() {
        return this.id;
    }
    
    public void setId(ExerciceDeSeanceId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public double getTempsExSc() {
        return this.tempsExSc;
    }
    
    public void setTempsExSc(double tempsExSc) {
        this.tempsExSc = tempsExSc;
    }
    public int getRepsExSc() {
        return this.repsExSc;
    }
    
    public void setRepsExSc(int repsExSc) {
        this.repsExSc = repsExSc;
    }
    public String getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }
    public String getAvisLibre() {
        return this.avisLibre;
    }
    
    public void setAvisLibre(String avisLibre) {
        this.avisLibre = avisLibre;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ExerciceDeSeance other = (ExerciceDeSeance) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }


}


