package pojo;
// Generated 20 févr. 2019 11:34:49 by Hibernate Tools 4.3.1



/**
 * ExerciceDeBilanId generated by hbm2java
 */
public class ExerciceDeBilanId  implements java.io.Serializable {


     private int codeEx;
     private int codeScBilan;

    public ExerciceDeBilanId() {
    }

    public ExerciceDeBilanId(int codeEx, int codeScBilan) {
       this.codeEx = codeEx;
       this.codeScBilan = codeScBilan;
    }
   
    public int getCodeEx() {
        return this.codeEx;
    }
    
    public void setCodeEx(int codeEx) {
        this.codeEx = codeEx;
    }
    public int getCodeScBilan() {
        return this.codeScBilan;
    }
    
    public void setCodeScBilan(int codeScBilan) {
        this.codeScBilan = codeScBilan;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExerciceDeBilanId) ) return false;
		 ExerciceDeBilanId castOther = ( ExerciceDeBilanId ) other; 
         
		 return (this.getCodeEx()==castOther.getCodeEx())
 && (this.getCodeScBilan()==castOther.getCodeScBilan());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeEx();
         result = 37 * result + this.getCodeScBilan();
         return result;
   }   


}


