package pojo;
// Generated 18 f�vr. 2019 15:54:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Integer codeEx;
     private String nomEx;
     private String descriptionEx;
     private String ressourceEx;
     private Double tempsBaseEx;
     private String repsBaseEx;
     private String typeEx;
     private String objectifsEx;
     private Set exerciceDeSeances = new HashSet(0);
     private Set exerciceDeBilans = new HashSet(0);

    public Exercice() {
    }

	
    public Exercice(String nomEx, String objectifsEx) {
        this.nomEx = nomEx;
        this.objectifsEx = objectifsEx;
    }
    public Exercice(String nomEx, String descriptionEx, String ressourceEx, Double tempsBaseEx, String repsBaseEx, String typeEx, String objectifsEx, Set exerciceDeSeances, Set exerciceDeBilans) {
       this.nomEx = nomEx;
       this.descriptionEx = descriptionEx;
       this.ressourceEx = ressourceEx;
       this.tempsBaseEx = tempsBaseEx;
       this.repsBaseEx = repsBaseEx;
       this.typeEx = typeEx;
       this.objectifsEx = objectifsEx;
       this.exerciceDeSeances = exerciceDeSeances;
       this.exerciceDeBilans = exerciceDeBilans;
    }
   
    public Integer getCodeEx() {
        return this.codeEx;
    }
    
    public void setCodeEx(Integer codeEx) {
        this.codeEx = codeEx;
    }
    public String getNomEx() {
        return this.nomEx;
    }
    
    public void setNomEx(String nomEx) {
        this.nomEx = nomEx;
    }
    public String getDescriptionEx() {
        return this.descriptionEx;
    }
    
    public void setDescriptionEx(String descriptionEx) {
        this.descriptionEx = descriptionEx;
    }
    public String getRessourceEx() {
        return this.ressourceEx;
    }
    
    public void setRessourceEx(String ressourceEx) {
        this.ressourceEx = ressourceEx;
    }
    public Double getTempsBaseEx() {
        return this.tempsBaseEx;
    }
    
    public void setTempsBaseEx(Double tempsBaseEx) {
        this.tempsBaseEx = tempsBaseEx;
    }
    public String getRepsBaseEx() {
        return this.repsBaseEx;
    }
    
    public void setRepsBaseEx(String repsBaseEx) {
        this.repsBaseEx = repsBaseEx;
    }
    public String getTypeEx() {
        return this.typeEx;
    }
    
    public void setTypeEx(String typeEx) {
        this.typeEx = typeEx;
    }
    public String getObjectifsEx() {
        return this.objectifsEx;
    }
    
    public void setObjectifsEx(String objectifsEx) {
        this.objectifsEx = objectifsEx;
    }
    public Set getExerciceDeSeances() {
        return this.exerciceDeSeances;
    }
    
    public void setExerciceDeSeances(Set exerciceDeSeances) {
        this.exerciceDeSeances = exerciceDeSeances;
    }
    public Set getExerciceDeBilans() {
        return this.exerciceDeBilans;
    }
    
    public void setExerciceDeBilans(Set exerciceDeBilans) {
        this.exerciceDeBilans = exerciceDeBilans;
    }




}


