package pojo;
// Generated 20 fvr. 2019 11:34:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * ProfilClient generated by hbm2java
 */
public class ProfilClient  implements java.io.Serializable {


     private Integer codeProfil;
     private String nomProfil;
     private Set programmes = new HashSet(0);
     private Set utilisateurs = new HashSet(0);
     private Set seances = new HashSet(0);

    public ProfilClient() {
    }

	
    public ProfilClient(String nomProfil) {
        this.nomProfil = nomProfil;
    }
    public ProfilClient(String nomProfil, Set programmes, Set utilisateurs, Set seances) {
       this.nomProfil = nomProfil;
       this.programmes = programmes;
       this.utilisateurs = utilisateurs;
       this.seances = seances;
    }
   
    public Integer getCodeProfil() {
        return this.codeProfil;
    }
    
    public void setCodeProfil(Integer codeProfil) {
        this.codeProfil = codeProfil;
    }
    public String getNomProfil() {
        return this.nomProfil;
    }
    
    public void setNomProfil(String nomProfil) {
        this.nomProfil = nomProfil;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }
    public Set getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set seances) {
        this.seances = seances;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.codeProfil);
        hash = 59 * hash + Objects.hashCode(this.nomProfil);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ProfilClient other = (ProfilClient) obj;
        if (!Objects.equals(this.nomProfil, other.nomProfil)) {
            return false;
        }
        if (!Objects.equals(this.codeProfil, other.codeProfil)) {
            return false;
        }
        return true;
    }


}


