package pojo;
// Generated 19 f�vr. 2019 12:13:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer codePrgrm;
     private ProfilClient profilClient;
     private String libellePrgrm;
     private Boolean estProgrammeClient;
     private Set seanceBilanAppartenirs = new HashSet(0);
     private Set seanceAppartenirs = new HashSet(0);

    public Programme() {
    }

	
    public Programme(String libellePrgrm) {
        this.libellePrgrm = libellePrgrm;
    }
    
    public Programme(ProfilClient profilClient, String libellePrgrm, Boolean estProgrammeClient, Set seanceBilanAppartenirs, Set seanceAppartenirs) {
       this.profilClient = profilClient;
       this.libellePrgrm = libellePrgrm;
       this.estProgrammeClient = estProgrammeClient;
       this.seanceBilanAppartenirs = seanceBilanAppartenirs;
       this.seanceAppartenirs = seanceAppartenirs;
    }
   
    public Integer getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(Integer codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public ProfilClient getProfilClient() {
        return this.profilClient;
    }
    
    public void setProfilClient(ProfilClient profilClient) {
        this.profilClient = profilClient;
    }

    public String getLibellePrgrm() {
        return this.libellePrgrm;
    }
    
    public void setLibellePrgrm(String libellePrgrm) {
        this.libellePrgrm = libellePrgrm;
    }
    public Boolean getEstProgrammeClient() {
        return this.estProgrammeClient;
    }
    
    public void setEstProgrammeClient(Boolean estProgrammeClient) {
        this.estProgrammeClient = estProgrammeClient;
    }
    public Set getSeanceBilanAppartenirs() {
        return this.seanceBilanAppartenirs;
    }
    
    public void setSeanceBilanAppartenirs(Set seanceBilanAppartenirs) {
        this.seanceBilanAppartenirs = seanceBilanAppartenirs;
    }
    public Set getSeanceAppartenirs() {
        return this.seanceAppartenirs;
    }
    
    public void setSeanceAppartenirs(Set seanceAppartenirs) {
        this.seanceAppartenirs = seanceAppartenirs;
    }
}


