package pojo;
// Generated 18 f�vr. 2019 15:54:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer codePrgrm;
     private ProfilClient profilClient;
     private String libellePrgrm;
     private Set semaines = new HashSet(0);

    public Programme() {
    }

	
    public Programme(String libellePrgrm) {
        this.libellePrgrm = libellePrgrm;
    }
    public Programme(ProfilClient profilClient, String libellePrgrm, Set semaines) {
       this.profilClient = profilClient;
       this.libellePrgrm = libellePrgrm;
       this.semaines = semaines;
    }
   
    public Integer getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(Integer codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public ProfilClient getProfilClient() {
        return this.profilClient;
    }
    
    public void setProfilClient(ProfilClient profilClient) {
        this.profilClient = profilClient;
    }
    
    public String getLibellePrgrm() {
        return this.libellePrgrm;
    }
    
    public void setLibellePrgrm(String libellePrgrm) {
        this.libellePrgrm = libellePrgrm;
    }
    public Set getSemaines() {
        return this.semaines;
    }
    
    public void setSemaines(Set semaines) {
        this.semaines = semaines;
    }
}


