package pojo;
// Generated 19 fvr. 2019 12:38:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SeanceBilan generated by hbm2java
 */
public class SeanceBilan  implements java.io.Serializable {


     private Integer codeScBilan;
     private Integer age;
     private Double poids;
     private Integer fcCinqminAll;
     private Integer fcTrenteflexions;
     private Integer fcUneminApexAll;
     private Boolean objectifMinceur;
     private Double mensBras;
     private Double mensPoitrine;
     private Double mensTaille;
     private Double mensHanches;
     private Double mensCuisses;
     private Set exerciceDeBilans = new HashSet(0);
     private Set seanceBilanAppartenirs = new HashSet(0);

    public SeanceBilan() {
    }

    public SeanceBilan(Integer age, Double poids, Integer fcCinqminAll, Integer fcTrenteflexions, Integer fcUneminApexAll, Boolean objectifMinceur, Double mensBras, Double mensPoitrine, Double mensTaille, Double mensHanches, Double mensCuisses, Set exerciceDeBilans, Set seanceBilanAppartenirs) {
       this.age = age;
       this.poids = poids;
       this.fcCinqminAll = fcCinqminAll;
       this.fcTrenteflexions = fcTrenteflexions;
       this.fcUneminApexAll = fcUneminApexAll;
       this.objectifMinceur = objectifMinceur;
       this.mensBras = mensBras;
       this.mensPoitrine = mensPoitrine;
       this.mensTaille = mensTaille;
       this.mensHanches = mensHanches;
       this.mensCuisses = mensCuisses;
       this.exerciceDeBilans = exerciceDeBilans;
       this.seanceBilanAppartenirs = seanceBilanAppartenirs;
    }
   
    public Integer getCodeScBilan() {
        return this.codeScBilan;
    }
    
    public void setCodeScBilan(Integer codeScBilan) {
        this.codeScBilan = codeScBilan;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Double getPoids() {
        return this.poids;
    }
    
    public void setPoids(Double poids) {
        this.poids = poids;
    }
    public Integer getFcCinqminAll() {
        return this.fcCinqminAll;
    }
    
    public void setFcCinqminAll(Integer fcCinqminAll) {
        this.fcCinqminAll = fcCinqminAll;
    }
    public Integer getFcTrenteflexions() {
        return this.fcTrenteflexions;
    }
    
    public void setFcTrenteflexions(Integer fcTrenteflexions) {
        this.fcTrenteflexions = fcTrenteflexions;
    }
    public Integer getFcUneminApexAll() {
        return this.fcUneminApexAll;
    }
    
    public void setFcUneminApexAll(Integer fcUneminApexAll) {
        this.fcUneminApexAll = fcUneminApexAll;
    }
    public Boolean getObjectifMinceur() {
        return this.objectifMinceur;
    }
    
    public void setObjectifMinceur(Boolean objectifMinceur) {
        this.objectifMinceur = objectifMinceur;
    }
    public Double getMensBras() {
        return this.mensBras;
    }
    
    public void setMensBras(Double mensBras) {
        this.mensBras = mensBras;
    }
    public Double getMensPoitrine() {
        return this.mensPoitrine;
    }
    
    public void setMensPoitrine(Double mensPoitrine) {
        this.mensPoitrine = mensPoitrine;
    }
    public Double getMensTaille() {
        return this.mensTaille;
    }
    
    public void setMensTaille(Double mensTaille) {
        this.mensTaille = mensTaille;
    }
    public Double getMensHanches() {
        return this.mensHanches;
    }
    
    public void setMensHanches(Double mensHanches) {
        this.mensHanches = mensHanches;
    }
    public Double getMensCuisses() {
        return this.mensCuisses;
    }
    
    public void setMensCuisses(Double mensCuisses) {
        this.mensCuisses = mensCuisses;
    }
    public Set getExerciceDeBilans() {
        return this.exerciceDeBilans;
    }
    
    public void setExerciceDeBilans(Set exerciceDeBilans) {
        this.exerciceDeBilans = exerciceDeBilans;
    }
    public Set getSeanceBilanAppartenirs() {
        return this.seanceBilanAppartenirs;
    }
    
    public void setSeanceBilanAppartenirs(Set seanceBilanAppartenirs) {
        this.seanceBilanAppartenirs = seanceBilanAppartenirs;
    }




}


