package pojo;
// Generated 19 févr. 2019 12:38:57 by Hibernate Tools 4.3.1



/**
 * SeanceBilanAppartenir generated by hbm2java
 */
public class SeanceBilanAppartenir  implements java.io.Serializable {


     private SeanceBilanAppartenirId id;
     private Programme programme;
     private SeanceBilan seanceBilan;

    public SeanceBilanAppartenir() {
    }

    public SeanceBilanAppartenir(SeanceBilanAppartenirId id, Programme programme, SeanceBilan seanceBilan) {
       this.id = id;
       this.programme = programme;
       this.seanceBilan = seanceBilan;
    }
   
    public SeanceBilanAppartenirId getId() {
        return this.id;
    }
    
    public void setId(SeanceBilanAppartenirId id) {
        this.id = id;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public SeanceBilan getSeanceBilan() {
        return this.seanceBilan;
    }
    
    public void setSeanceBilan(SeanceBilan seanceBilan) {
        this.seanceBilan = seanceBilan;
    }




}


