package pojo;
// Generated 21 févr. 2019 10:27:40 by Hibernate Tools 4.3.1



/**
 * SeanceAppartenirId generated by hbm2java
 */
public class SeanceAppartenirId  implements java.io.Serializable {


     private int codeSc;
     private int codePrgrm;
     private int noSemaine;
     private int ordre;

    public SeanceAppartenirId() {
    }

    public SeanceAppartenirId(int codeSc, int codePrgrm, int noSemaine, int ordre) {
       this.codeSc = codeSc;
       this.codePrgrm = codePrgrm;
       this.noSemaine = noSemaine;
       this.ordre = ordre;
    }
   
    public int getCodeSc() {
        return this.codeSc;
    }
    
    public void setCodeSc(int codeSc) {
        this.codeSc = codeSc;
    }
    public int getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(int codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public int getNoSemaine() {
        return this.noSemaine;
    }
    
    public void setNoSemaine(int noSemaine) {
        this.noSemaine = noSemaine;
    }
    public int getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(int ordre) {
        this.ordre = ordre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeanceAppartenirId) ) return false;
		 SeanceAppartenirId castOther = ( SeanceAppartenirId ) other; 
         
		 return (this.getCodeSc()==castOther.getCodeSc())
 && (this.getCodePrgrm()==castOther.getCodePrgrm())
 && (this.getNoSemaine()==castOther.getNoSemaine())
 && (this.getOrdre()==castOther.getOrdre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeSc();
         result = 37 * result + this.getCodePrgrm();
         result = 37 * result + this.getNoSemaine();
         result = 37 * result + this.getOrdre();
         return result;
   }   


}


