package pojo;
// Generated 20 fvr. 2019 13:58:26 by Hibernate Tools 4.3.1



/**
 * SeanceAppartenirId generated by hbm2java
 */
public class SeanceAppartenirId  implements java.io.Serializable {


     private int codePrgrm;
     private int codeSc;
     private int codeSemaine;
     private int ordre;

    public SeanceAppartenirId() {
    }

    public SeanceAppartenirId(int codePrgrm, int codeSc, int codeSemaine, int ordre) {
       this.codePrgrm = codePrgrm;
       this.codeSc = codeSc;
       this.codeSemaine = codeSemaine;
       this.ordre = ordre;
    }
   
    public int getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(int codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public int getCodeSc() {
        return this.codeSc;
    }
    
    public void setCodeSc(int codeSc) {
        this.codeSc = codeSc;
    }
    public int getCodeSemaine() {
        return this.codeSemaine;
    }
    
    public void setCodeSemaine(int codeSemaine) {
        this.codeSemaine = codeSemaine;
    }
    public int getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(int ordre) {
        this.ordre = ordre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeanceAppartenirId) ) return false;
		 SeanceAppartenirId castOther = ( SeanceAppartenirId ) other; 
         
		 return (this.getCodePrgrm()==castOther.getCodePrgrm())
 && (this.getCodeSc()==castOther.getCodeSc())
 && (this.getCodeSemaine()==castOther.getCodeSemaine())
 && (this.getOrdre()==castOther.getOrdre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodePrgrm();
         result = 37 * result + this.getCodeSc();
         result = 37 * result + this.getCodeSemaine();
         result = 37 * result + this.getOrdre();
         return result;
   }   


}


