package pojo;
// Generated 20 fvr. 2019 13:58:26 by Hibernate Tools 4.3.1



/**
 * SeanceBilanAppartenirId generated by hbm2java
 */
public class SeanceBilanAppartenirId  implements java.io.Serializable {


     private int codeScBilan;
     private int codePrgrm;
     private int codeSemaine;

    public SeanceBilanAppartenirId() {
    }

    public SeanceBilanAppartenirId(int codeScBilan, int codePrgrm, int codeSemaine) {
       this.codeScBilan = codeScBilan;
       this.codePrgrm = codePrgrm;
       this.codeSemaine = codeSemaine;
    }
   
    public int getCodeScBilan() {
        return this.codeScBilan;
    }
    
    public void setCodeScBilan(int codeScBilan) {
        this.codeScBilan = codeScBilan;
    }
    public int getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(int codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public int getCodeSemaine() {
        return this.codeSemaine;
    }
    
    public void setCodeSemaine(int codeSemaine) {
        this.codeSemaine = codeSemaine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeanceBilanAppartenirId) ) return false;
		 SeanceBilanAppartenirId castOther = ( SeanceBilanAppartenirId ) other; 
         
		 return (this.getCodeScBilan()==castOther.getCodeScBilan())
 && (this.getCodePrgrm()==castOther.getCodePrgrm())
 && (this.getCodeSemaine()==castOther.getCodeSemaine());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeScBilan();
         result = 37 * result + this.getCodePrgrm();
         result = 37 * result + this.getCodeSemaine();
         return result;
   }   


}


