package pojo;
// Generated 20 fvr. 2019 11:34:49 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * SeanceBilanAppartenir generated by hbm2java
 */
public class SeanceBilanAppartenir  implements java.io.Serializable {


     private SeanceBilanAppartenirId id;
     private Programme programme;
     private SeanceBilan seanceBilan;

    public SeanceBilanAppartenir() {
    }

    public SeanceBilanAppartenir(SeanceBilanAppartenirId id, Programme programme, SeanceBilan seanceBilan) {
       this.id = id;
       this.programme = programme;
       this.seanceBilan = seanceBilan;
    }
   
    public SeanceBilanAppartenirId getId() {
        return this.id;
    }
    
    public void setId(SeanceBilanAppartenirId id) {
        this.id = id;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public SeanceBilan getSeanceBilan() {
        return this.seanceBilan;
    }
    
    public void setSeanceBilan(SeanceBilan seanceBilan) {
        this.seanceBilan = seanceBilan;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SeanceBilanAppartenir other = (SeanceBilanAppartenir) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


