package pojo;
// Generated 19 fvr. 2019 12:38:57 by Hibernate Tools 4.3.1



/**
 * SeanceAppartenir generated by hbm2java
 */
public class SeanceAppartenir  implements java.io.Serializable {


     private SeanceAppartenirId id;
     private Programme programme;
     private Seance seance;

    public SeanceAppartenir() {
    }

    public SeanceAppartenir(SeanceAppartenirId id, Programme programme, Seance seance) {
       this.id = id;
       this.programme = programme;
       this.seance = seance;
    }
   
    public SeanceAppartenirId getId() {
        return this.id;
    }
    
    public void setId(SeanceAppartenirId id) {
        this.id = id;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }




}


