package pojo;
// Generated 18 févr. 2019 15:54:11 by Hibernate Tools 4.3.1



/**
 * SemaineId generated by hbm2java
 */
public class SemaineId  implements java.io.Serializable {


     private int codePrgrm;
     private int codeSc;
     private int numero;

    public SemaineId() {
    }

    public SemaineId(int codePrgrm, int codeSc, int numero) {
       this.codePrgrm = codePrgrm;
       this.codeSc = codeSc;
       this.numero = numero;
    }
   
    public int getCodePrgrm() {
        return this.codePrgrm;
    }
    
    public void setCodePrgrm(int codePrgrm) {
        this.codePrgrm = codePrgrm;
    }
    public int getCodeSc() {
        return this.codeSc;
    }
    
    public void setCodeSc(int codeSc) {
        this.codeSc = codeSc;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemaineId) ) return false;
		 SemaineId castOther = ( SemaineId ) other; 
         
		 return (this.getCodePrgrm()==castOther.getCodePrgrm())
 && (this.getCodeSc()==castOther.getCodeSc())
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodePrgrm();
         result = 37 * result + this.getCodeSc();
         result = 37 * result + this.getNumero();
         return result;
   }   


}


