package pojo;
// Generated 18 févr. 2019 15:54:11 by Hibernate Tools 4.3.1



/**
 * Semaine generated by hbm2java
 */
public class Semaine  implements java.io.Serializable {


     private SemaineId id;
     private Programme programme;
     private Seance seance;

    public Semaine() {
    }

    public Semaine(SemaineId id, Programme programme, Seance seance) {
       this.id = id;
       this.programme = programme;
       this.seance = seance;
    }
   
    public SemaineId getId() {
        return this.id;
    }
    
    public void setId(SemaineId id) {
        this.id = id;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }




}


