package pojo;
// Generated 20 fvr. 2019 11:34:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * TypeExercice generated by hbm2java
 */
public class TypeExercice  implements java.io.Serializable {


     private Integer codeTypeEx;
     private String libTypeEx;
     private Set exercices = new HashSet(0);

    public TypeExercice() {
    }

	
    public TypeExercice(String libTypeEx) {
        this.libTypeEx = libTypeEx;
    }
    public TypeExercice(String libTypeEx, Set exercices) {
       this.libTypeEx = libTypeEx;
       this.exercices = exercices;
    }
   
    public Integer getCodeTypeEx() {
        return this.codeTypeEx;
    }
    
    public void setCodeTypeEx(Integer codeTypeEx) {
        this.codeTypeEx = codeTypeEx;
    }
    public String getLibTypeEx() {
        return this.libTypeEx;
    }
    
    public void setLibTypeEx(String libTypeEx) {
        this.libTypeEx = libTypeEx;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.codeTypeEx);
        hash = 97 * hash + Objects.hashCode(this.libTypeEx);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TypeExercice other = (TypeExercice) obj;
        if (!Objects.equals(this.libTypeEx, other.libTypeEx)) {
            return false;
        }
        if (!Objects.equals(this.codeTypeEx, other.codeTypeEx)) {
            return false;
        }
        return true;
    }


}


