package pojo;
// Generated 19 févr. 2019 12:38:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TypeExercice generated by hbm2java
 */
public class TypeExercice  implements java.io.Serializable {


     private Integer codeTypeEx;
     private String libTypeEx;
     private Set exercices = new HashSet(0);

    public TypeExercice() {
    }

	
    public TypeExercice(String libTypeEx) {
        this.libTypeEx = libTypeEx;
    }
    public TypeExercice(String libTypeEx, Set exercices) {
       this.libTypeEx = libTypeEx;
       this.exercices = exercices;
    }
   
    public Integer getCodeTypeEx() {
        return this.codeTypeEx;
    }
    
    public void setCodeTypeEx(Integer codeTypeEx) {
        this.codeTypeEx = codeTypeEx;
    }
    public String getLibTypeEx() {
        return this.libTypeEx;
    }
    
    public void setLibTypeEx(String libTypeEx) {
        this.libTypeEx = libTypeEx;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }




}


